[package]
name = "send_email"
version = "0.1.0"
authors = ["1di0t <dgqcjx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10.0-alpha.1"
chrono = "0.4.13"
